services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - db

  data_ingestion_service:
    build:
      context: ../data_ingestion_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ../data_ingestion_service:/app
    env_file:
      - ../data_ingestion_service/.env
    networks:
      - app_network
    depends_on:
      - db
      - auth_service

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
